export {default as Bg} from "./Bg"
export {default as Card} from "./Card"
export {default as Info} from "./Info"
export {default as Name} from "./Name"
export {default as ProfileContet} from "./ProfileContet"